"""
Data annotation overlay for Moonshot.

Draws location, moon phase, weather, and timestamp information onto
the final rendered image using PIL text rendering.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from PIL import Image, ImageDraw, ImageFont


@dataclass
class LocationData:
    """Location information for annotations.

    Attributes:
        city: City name (or empty string).
        state: State name/code (or empty string).
        lat: Latitude in decimal degrees.
        lon: Longitude in decimal degrees.
    """
    city: str = ""
    state: str = ""
    country: str = ""
    lat: float = 0.0
    lon: float = 0.0


@dataclass
class MoonData:
    """Moon observation data for annotations.

    Attributes:
        illumination_pct: Illuminated percentage (0–100).
        altitude_deg: Apparent altitude in degrees.
        azimuth_deg: Apparent azimuth in degrees.
        phase_name: Human-readable phase name.
    """
    illumination_pct: float = 0.0
    altitude_deg: float = 0.0
    azimuth_deg: float = 0.0
    phase_name: str = ""


@dataclass
class WeatherAnnotationData:
    """Weather data for annotations.

    Attributes:
        temp_c: Temperature in degrees Celsius.
        conditions: Weather description (e.g. "Overcast").
        wind_speed_ms: Wind speed in metres per second.
        humidity_pct: Relative humidity percentage.
    """
    temp_c: float = 0.0
    conditions: str = ""
    wind_speed_ms: float = 0.0
    humidity_pct: float = 0.0


@dataclass
class TimeData:
    """Date/time information for annotations.

    Attributes:
        date_str: Date string (e.g. "2026-04-27").
        time_str: Time string (e.g. "21:00").
        timezone_str: Timezone name (e.g. "America/New_York").
    """
    date_str: str = ""
    time_str: str = ""
    timezone_str: str = ""


# ---------------------------------------------------------------------------
#  Font helpers
# ---------------------------------------------------------------------------

def _get_font(size: int) -> ImageFont.FreeTypeFont:
    """Try to load a suitable monospace truetype font.

    Falls back to PIL default if no TTF is available.
    """
    try:
        return ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", size)
    except (IOError, OSError):
        try:
            return ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", size)
        except (IOError, OSError):
            return ImageFont.load_default()


# ---------------------------------------------------------------------------
#  Text drawing helper
# ---------------------------------------------------------------------------

def _draw_text_with_background(
    draw: ImageDraw.ImageDraw,
    xy: tuple,
    text: str,
    font: ImageFont.FreeTypeFont,
    text_colour: tuple = (255, 255, 255),
    bg_colour: tuple = (0, 0, 0),
    bg_padding: int = 4,
    anchor: Optional[str] = None,
) -> None:
    """Draw text with a semi-transparent dark background for readability.

    Args:
        draw: PIL ``ImageDraw`` instance.
        xy: ``(x, y)`` position.
        text: Text string to draw.
        font: PIL ``ImageFont``.
        text_colour: RGB tuple for text.
        bg_colour: RGB tuple for background.
        bg_padding: Padding around text in pixels.
        anchor: PIL text anchor (e.g. "la", "ra", "ma", "mt").
    """
    # Measure text bounds
    bbox = draw.textbbox(xy, text, font=font, anchor=anchor)
    # Draw background rectangle
    bg_rect = (
        bbox[0] - bg_padding,
        bbox[1] - bg_padding,
        bbox[2] + bg_padding,
        bbox[3] + bg_padding,
    )
    draw.rectangle(bg_rect, fill=(*bg_colour, 120))  # semi-transparent (if RGBA)
    # Draw text
    draw.text(xy, text, font=font, fill=(*text_colour, 255), anchor=anchor)


# ---------------------------------------------------------------------------
#  Main annotation function
# ---------------------------------------------------------------------------

def annotate_image(image: Image.Image,
                   location_data: LocationData,
                   moon_data: MoonData,
                   weather_data: WeatherAnnotationData,
                   time_data: TimeData) -> Image.Image:
    """Overlay data annotations on the rendered image.

    Annotations include:

    * **Header:** ``"Location • Date/Time"`` centred at top
    * **Left panel:** Moon phase details (illumination, altitude, azimuth)
    * **Right panel:** Weather conditions (temperature, conditions, wind)
    * **Footer:** ``"Generated by Moonshot"`` centred at bottom

    All text is white on a subtle dark semi-transparent background for
    readability against any sky colour.

    Args:
        image: Input PIL ``Image`` (RGB or RGBA).
        location_data: ``LocationData`` with city/state info.
        moon_data: ``MoonData`` with phase/position info.
        weather_data: ``WeatherAnnotationData`` with weather info.
        time_data: ``TimeData`` with date/time info.

    Returns:
        A new PIL ``Image`` (RGBA mode) with annotations overlaid.
    """
    base = image.convert("RGBA")
    w, h = base.size

    # Create an overlay layer for the text backgrounds
    overlay = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    # Font sizes (relative to image height)
    header_size = max(16, h // 40)
    body_size = max(14, h // 50)
    footer_size = max(12, h // 60)

    header_font = _get_font(header_size)
    body_font = _get_font(body_size)
    footer_font = _get_font(footer_size)

    margin = int(w * 0.02)
    line_spacing = body_size + 6

    # --- Header: "Location • Date Time" ---
    parts = []
    if location_data.city:
        parts.append(location_data.city)
    if location_data.state:
        parts.append(location_data.state)
    if location_data.country:
        parts.append(location_data.country)
    if parts:
        city_str = ", ".join(parts)
    else:
        city_str = f"{location_data.lat:.2f}, {location_data.lon:.2f}"
    header_text = f"{city_str}  •  {time_data.date_str} {time_data.time_str} {time_data.timezone_str}"
    _draw_text_with_background(
        draw,
        (w // 2, margin),
        header_text,
        header_font,
        anchor="mt",
    )

    # --- Left panel: Moon data ---
    left_x = margin
    left_y = margin + header_size + line_spacing

    moon_lines = [
        f"Moon: {moon_data.illumination_pct:.1f}%  •  {moon_data.phase_name}",
        f"Alt {moon_data.altitude_deg:.1f}°  •  Az {moon_data.azimuth_deg:.1f}°",
    ]
    # If valid phase name, use it; otherwise just show generic
    for line in moon_lines:
        bbox = draw.textbbox((0, 0), line, font=body_font)
        _draw_text_with_background(
            draw,
            (left_x, left_y),
            line,
            body_font,
            anchor="la",
        )
        left_y += line_spacing

    # --- Right panel: Weather data ---
    right_x = w - margin
    right_y = margin + header_size + line_spacing

    weather_lines = [
        f"{weather_data.temp_c:.0f}°C  •  {weather_data.conditions}",
        f"{weather_data.wind_speed_ms:.1f} m/s  •  {weather_data.humidity_pct:.0f}%",
    ]
    for line in weather_lines:
        _draw_text_with_background(
            draw,
            (right_x, right_y),
            line,
            body_font,
            anchor="ra",
        )
        right_y += line_spacing

    # --- Footer: "Generated by Moonshot" ---
    footer_text = "Generated by Moonshot"
    _draw_text_with_background(
        draw,
        (w // 2, h - margin - footer_size),
        footer_text,
        footer_font,
        anchor="mb",
    )

    # Composite the overlay onto the base
    result = Image.alpha_composite(base, overlay)
    return result
